package triage

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

type buf struct{ lines []string }

func (b *buf) w(f string, a ...any) {
	if len(a) == 0 {
		b.lines = append(b.lines, f)
		return
	}
	b.lines = append(b.lines, fmt.Sprintf(f, a...))
}

// s appends a line that is already text, so a stray % in a finding's own
// prose is not read as a format verb.
func (b *buf) s(line string) { b.lines = append(b.lines, line) }

func h(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

// InputSummary describes what a maintainer would find in the directory.
func InputSummary(f Finding) string {
	var bits []string
	if n := len(f.Inputs); n > 0 {
		bits = append(bits, fmt.Sprintf("%d file%s", n, plural(n)))
	}
	if f.SQLBlocks > 0 {
		bits = append(bits, fmt.Sprintf("%d inline SQL block%s", f.SQLBlocks, plural(f.SQLBlocks)))
	}
	if len(bits) == 0 {
		return "**none**"
	}
	return strings.Join(bits, ", ")
}

var wsCollapse = regexp.MustCompile(`\s+`)

// Render writes the whole document.
func Render(findings []Finding, lifts []Lead, censuses []Census,
	accFiles map[string]bool, accRows []AcceptRow) string {

	b := &buf{}
	byArea := map[string][]Finding{}
	for _, f := range findings {
		byArea[f.Area] = append(byArea[f.Area], f)
	}
	total := len(findings)

	b.w("# Reporting triage")
	b.w("")
	b.w("Generated by `pgfuzz triage-report` from the record: the finding")
	b.w("directories, each README's own fields, what is actually on disk, and the")
	b.w("campaign censuses. Do not edit this file -- edit the generator.")
	b.w("")
	var counts []string
	for _, a := range Areas {
		counts = append(counts, fmt.Sprintf("%s %d", a, len(byArea[a])))
	}
	b.w("**%d findings.** %s", total, strings.Join(counts, " · "))
	b.w("")
	b.w("The campaign report publishes this same count and has published it")
	b.w("wrong twice, which is why it is generated here rather than written:")
	b.w("")
	b.w("- `FINDINGS/.git` is a directory, because FINDINGS is its own repo, and")
	b.w("  both filters in the report skipped `20*-` and `reports/` but")
	b.w("  not dotfiles. It was counted as a PostgreSQL-core finding, and as")
	b.w(`  "not attributable from the write-up" in the per-target table.`)
	// ONLY FOR FINDINGS THAT ARE ACTUALLY HERE. AttribOverride is a static
	// map, so a scoped document explained the re-attribution of a finding it
	// had just excluded -- a note about something the reader cannot see, in
	// the one section whose job is explaining why the count is what it is.
	present := make(map[string]bool, len(findings))
	for _, f := range findings {
		present[f.Name] = true
	}
	var ovNames []string
	for n := range AttribOverride {
		if present[n] {
			ovNames = append(ovNames, n)
		}
	}
	sort.Strings(ovNames)
	for _, n := range ovNames {
		v := AttribOverride[n]
		b.w("- `%s` is counted under **%s**: %s.", n, v[0], v[1])
	}
	b.w("")
	b.w("**One row is not one defect.** `oss-fuzz-harness-bugs` is a single")
	b.w("directory holding fourteen numbered sub-defects; the campaign report's")
	b.w("narrative section counts twelve of them individually while this count")
	b.w("treats the directory as one. Both are defensible. Neither says which it")
	b.w("is, and that is the thing to fix in the report.")
	b.w("")
	b.w("Two questions decide reportability and are asked separately, because")
	b.w("the answers differ: **is it confirmed**, and **is there an input**. Not")
	b.w("every input is a file -- a four-statement script, a GUC left at its")
	b.w("default, and a build recipe are all inputs, and the input column below")
	b.w("counts files, so read the entry before concluding a finding has nothing.")
	b.w("")
	b.w("**Nothing here has been re-reproduced.** Every status is the record's")
	b.w("word, as written.")
	b.w("")

	b.w("## Index")
	b.w("")
	b.w("| # | finding | area | repro | cause |")
	b.w("|---|---|---|---|---|")
	for i, f := range findings {
		rv := "**none**"
		if f.ReproSrc != "" {
			rv = f.ReproSrc
		}
		cause := "**not stated**"
		if f.Cause != "" {
			cause = "yes"
		}
		b.w("| %d | [%s](#%s) | %s | %s | %s |", i+1, f.Name, f.Name, f.Area, rv, cause)
	}
	b.w("")

	var norepro, nocause []string
	for _, f := range findings {
		if f.Repro == "" {
			norepro = append(norepro, "`"+f.Name+"`")
		}
		if f.Cause == "" {
			nocause = append(nocause, "`"+f.Name+"`")
		}
	}
	if len(norepro) > 0 {
		b.w("**%d have no repro vector** — no runnable block in the", len(norepro))
		b.w("write-up and no `.sql` or `repro*` file on disk: %s.", strings.Join(norepro, ", "))
		b.w("Some of those are correct — a finding about a budget spent on")
		b.w("replay has nothing to run. The rest are write-ups that describe a")
		b.w("defect without saying how to see it, and that is the gap between")
		b.w("a finding and a report.")
		b.w("")
	}
	if len(nocause) > 0 {
		b.w("**%d state no cause** under any of the headings this", len(nocause))
		b.w("reads (`Mechanism`, `The defect`, `Cause`, `Root cause`, `What")
		b.w("happens`): %s.", strings.Join(nocause, ", "))
		b.w("")
	}

	for _, a := range Areas {
		rows := byArea[a]
		if len(rows) == 0 {
			continue
		}
		b.w("## %s — %d", a, len(rows))
		b.w("")
		for _, f := range rows {
			b.w("<a id=\"%s\"></a>", f.Name)
			b.w("")
			b.w("### %s", f.Title)
			b.w("")
			line := "`" + f.Name + "`"
			if f.Where != "" {
				line += " · " + f.Where
			}
			if f.FoundBy != "" {
				line += " · found by " + f.FoundBy
			}
			b.s(line)
			b.w("")
			if f.Repro != "" {
				lang := "bash"
				if sqlStart.MatchString(f.Repro) {
					lang = "sql"
				}
				suffix := ""
				if f.ReproSrc != "stated" {
					suffix = fmt.Sprintf(" _(%s)_", f.ReproSrc)
				}
				b.w("**Repro**%s", suffix)
				b.w("")
				b.w("```%s", lang)
				b.s(f.Repro)
				b.w("```")
			} else {
				b.w("**Repro:** none — nothing runnable in the write-up, no " +
					"`.sql` or `repro*` file on disk.")
			}
			b.w("")
			if f.Cause != "" {
				b.w("**Cause.** %s", f.Cause)
			} else {
				b.w("**Cause:** not stated under any heading this reads.")
			}
			b.w("")
			var bits []string
			if f.Affects != "" {
				bits = append(bits, "affects "+f.Affects)
			}
			if f.Status != "" {
				bits = append(bits, wsCollapse.ReplaceAllString(f.Status, " "))
			}
			if n := len(f.Inputs); n > 0 {
				bits = append(bits, fmt.Sprintf("%d artefact%s", n, plural(n)))
			}
			if len(bits) > 0 {
				b.s("_" + strings.Join(bits, " · ") + "_")
				b.w("")
			}
			if f.Override != nil {
				b.w("> Counted under %s — %s. "+
					"The directory name still says otherwise, which is how it "+
					"gets reported to the wrong project.", f.Override[0], f.Override[1])
				b.w("")
			}
			for _, wrn := range f.Warns {
				if wrn == "not reported upstream" {
					continue
				}
				b.w("> The write-up says: **%s**", wrn)
				b.w("")
			}
		}
	}

	b.w("## Seen on vanilla PostgreSQL 17, explained by no finding")
	b.w("")
	b.w("The point of running a vanilla arm alongside the forks is that a fault")
	b.w("landing on stock PostgreSQL is PostgreSQL's, whichever campaign happened")
	b.w("to be running when it did. These signatures did land there, in a family")
	b.w("containing `pg17`, on a workspace with no fork patches and no extension.")
	b.w("")
	var accNames []string
	for f := range accFiles {
		accNames = append(accNames, "`"+f+"`")
	}
	sort.Strings(accNames)
	b.w("Already excluded, and worth stating because it is most of the volume:")
	b.w("**the accepted `-fwrapv` sites.** PostgreSQL compiles with `-fwrapv`,")
	b.w("so signed overflow is *defined to wrap* in the binaries it ships. Six")
	b.w("sites are catalogued in `scripts/ubsan-baseline.tsv` and gated by")
	b.w("the UBSan gate; every signed-overflow report in %s is one of them and",
		strings.Join(accNames, ", "))
	b.w("is dropped here. Matching is by file where the baseline keys on")
	b.w("function, so this can only over-accept — a site called accepted is one")
	b.w("the gate has also seen.")
	b.w("")

	var leaks, real []Lead
	for _, e := range lifts {
		if e.Class == "leak" {
			leaks = append(leaks, e)
		} else {
			real = append(real, e)
		}
	}

	if len(leaks) > 0 {
		lh := 0
		for _, e := range leaks {
			lh += e.Hits
		}
		b.w("Also excluded: **%d LeakSanitizer signatures, %d hits**", len(leaks), lh)
		b.w("between them. Leak detection was taken out of the run path on")
		b.w("2026-08-07, and these are why: they are dominated by allocations the")
		b.w("harness never frees between inputs, not by anything PostgreSQL does")
		b.w("wrong. Two findings above already cover that ground, and one of them")
		b.w("says in its own title that the site it names is almost certainly")
		b.w("wrong. Listing them individually would manufacture %d leads from one known problem. The busiest:", len(leaks))
		b.w("")
		b.w("| hits | signature | vanilla workspaces |")
		b.w("|---:|---|---|")
		for i, e := range leaks {
			if i >= 5 {
				break
			}
			v := append([]string(nil), e.Vanilla...)
			sort.Strings(v)
			if len(v) > 3 {
				v = v[:3]
			}
			b.w("| %d | `%s` | %s |", e.Hits, e.Sig, strings.Join(v, ", "))
		}
		b.w("")
	}

	if len(real) == 0 {
		b.w("Nothing survives that filter.")
		b.w("")
	} else {
		label := map[string][2]string{
			"memory": {"Memory safety", "A heap or stack error on stock " +
				"PostgreSQL is the highest-value thing this list can " +
				"contain, and the only class here that would be a " +
				"security report."},
			"assert": {"Assertions", "An internal self-check firing on stock " +
				"PostgreSQL. Reachable-or-not is the whole question: " +
				"these are compiled out of shipped binaries."},
			"arith": {"Arithmetic not on the accept-list", "Signed overflow " +
				"in files `ubsan-baseline.tsv` does not cover. Probably " +
				"the same `-fwrapv` class as the accepted six, in which " +
				"case the honest outcome is six more baseline rows " +
				"rather than six findings -- but nobody has looked, and " +
				"that is exactly what the gate is for."},
			"other": {"Everything else", ""},
		}
		for _, cls := range []string{"memory", "assert", "arith", "other"} {
			var rows []Lead
			for _, e := range real {
				if e.Class == cls {
					rows = append(rows, e)
				}
			}
			if len(rows) == 0 {
				continue
			}
			b.w("### %s — %d", label[cls][0], len(rows))
			b.w("")
			if label[cls][1] != "" {
				b.s(label[cls][1])
				b.w("")
			}
			b.w("| hits | source | targets | vanilla workspaces | " +
				"artefacts | signature |")
			b.w("|---:|---|---|---|---|---|")
			for _, e := range rows {
				na := 0
				for _, a := range e.Artefacts {
					na += a.N
				}
				aw := "none kept"
				if na > 0 {
					aw = fmt.Sprintf("**%d** in %d dir%s", na, len(e.Artefacts),
						plural(len(e.Artefacts)))
				}
				b.w("| %d | `%s` | %s | %s | %s | `%s` |",
					e.Hits, h(e.Src), joinTop(e.Targets, 4), joinTop(e.Vanilla, 4),
					aw, clip(e.Sig, 90))
			}
			b.w("")
			seen := map[string]bool{}
			var paths []string
			for _, e := range rows {
				for _, a := range e.Artefacts {
					if !seen[a.Path] {
						seen[a.Path] = true
						paths = append(paths, a.Path)
					}
				}
			}
			sort.Strings(paths)
			if len(paths) > 0 {
				b.w("Artefacts for this class:")
				b.w("")
				for i, x := range paths {
					if i >= 8 {
						break
					}
					b.w("- `%s/`", x)
				}
				if len(paths) > 8 {
					b.w("- …and %d more", len(paths)-8)
				}
				b.w("")
			}
		}
		hits := 0
		for _, e := range real {
			hits += e.Hits
		}
		b.w("**%d signatures, %d hits, no", len(real), hits)
		b.w("finding behind any of them.** Each needs the same two questions")
		b.w("asked: does an artefact still exist, and does it reproduce on a")
		b.w("current stock build. Until both are answered these are leads, not")
		b.w("findings -- a signature is not a defect until somebody has looked")
		b.w("at it, and that is the rule this campaign has broken in both")
		b.w("directions already.")
		b.w("")
	}

	b.w("## Provenance")
	b.w("")
	for _, c := range censuses {
		b.w("- `%s` — %d distinct signatures", c.Campaign, len(c.Sigs))
	}
	b.w("- UBSan accept-list — %d sites, `scripts/ubsan-baseline.tsv`", len(accRows))
	b.w("")
	return strings.Join(b.lines, "\n") + "\n"
}

func joinTop(xs []string, n int) string {
	s := append([]string(nil), xs...)
	sort.Strings(s)
	if len(s) > n {
		s = s[:n]
	}
	return strings.Join(s, ", ")
}

func clip(s string, n int) string {
	if len(s) > n {
		return s[:n]
	}
	return s
}

// Sort orders findings by area, then name -- the order the document prints
// them in.
func Sort(fs []Finding) {
	sort.SliceStable(fs, func(i, j int) bool {
		ai, aj := areaIndex(fs[i].Area), areaIndex(fs[j].Area)
		if ai != aj {
			return ai < aj
		}
		return fs[i].Name < fs[j].Name
	})
}

func areaIndex(a string) int {
	for i, x := range Areas {
		if x == a {
			return i
		}
	}
	return len(Areas)
}
